booklab2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.bookhome,name='home'),
    path('',views.bookhome.as_view(),name='home'),
    path('detail/<int:pk>',views.bookdetail.as_view(),name='detail'),
    path('create/',views.bookcreate.as_view(),name='create'),                                              
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class bloglab(models.Model):
    title = models.CharField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField()

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

myapp/forms.py
from django import forms
from .models import bloglab

class Mybloglab(forms.ModelForm):

    class Meta:
        model = bloglab
        fields=['title','content','photo']
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),
    'content':forms.Textarea(attrs={'class':'form-control'}),
    'photo':forms.ImageField(),
     
    }
    
    

myapp/views.py
from django.shortcuts import render
from .models import bloglab
from.forms import Mybloglab
from django .views.generic import CreateView,ListView,DetailView
# Create your views here.
#def bookhome(request):
    #book_data=bloglab.object.all()
    #return render(request, 'myapp/home.html',{'show',book_data})

class bookhome(ListView):
    model=bloglab
    fields=['title','updated_on','content','created_on','photo']
    template_name='myapp/home.html'

class bookdetail(DetailView):
    model=bloglab
    fields=['title','updated_on','content','created_on','photo']
    template_name='myapp/detail.html'
    success_url='/detail/'

class bookcreate(CreateView):
    model=bloglab
    fields=['title','content','photo']
    template_name= 'myapp/create.html'
    success_url='/create/'

myapp/templates/myapp/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library Management Book Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1 class="text-center">Library Management Book Website</h1>
      <div class="row">
        <div class="col-sm-6">
          <h2>Search Books</h2>
          <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="submit">
        </form>
            <div class="form-group"></div>
            </div>
        </div>
      </div>
    </div>
  </body>
</html>

myapp/templates/myapp/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Item-Detail</title>
</head>
<body>
  <form action="" method="Post"enctype="multipart/form-data">
    {% csrf_token %}
  

<div class="card mb-3" style="max-width: 1500px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{bloglab.photo.url}}" class="img-fluid rounded-start" alt="...">
        <div class="card-footer">
            
        </div>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{bloglab.title}}</h5>
          <h1>Detail</h1>
          <p class="card-text">{{bloglab.content}}</p>
          <p class="card-text"><small class="text-muted"><h5> Date {{bloglab.created_on}}</h5></small></p>
        
          
 
          
        </div>
      </div>
    </div>
  </div>
</form>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/myapp/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Book Library</title>
</head>
<body>
    <div class="container">
     <br> <a href="" class="card-text"><h5> Book Literature 2</h5>
        <a href="" class="card-text"> <h5> Book Science 3  </h5>
            <a href="{% url 'create' %}" class="card-text"> <h5> create new book  </h5>
               

    <br> <div class="row">
        {% for bloglab in bloglab_list %}
    <div class="col-sm-6">
    <div class="card m-2">
   <img   src="{{bloglab.photo.url}}" class="card-img-top" alt="..." height="200"> </img> 
</div>
</div>
</div>
    <a href="{% url 'detail' bloglab.pk %}" class="card-text"><h5>{{bloglab.title}}</h5>
    <p>{{bloglab.content}}</p>
   <a href="" class="card-text"><p>Date {{bloglab.created_on}}</p></a>

   {% endfor %}
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>           